/**
 * Daily Brutal Quotes — Quote Engine
 * Deterministic quote selection based on UTC date.
 * Same quote is shown to all users on the same day globally.
 */

const QUOTES = [
  "Action is the only language reality understands.",
  "The anvil outlasts the hammer.",
  "Motivation is a guest; discipline is the host.",
  "You cannot conquer the mountain by staring at the peak.",
  "A sharp mind is forged in the fires of boredom.",
  "What you tolerate, you become.",
  "Silence the crowd, and you will hear your purpose.",
  "The heaviest weight you will ever lift is your own excuse.",
  "Time forgives nothing, but it rewards focus.",
  "A master builds his empire with the stones others threw at him.",
  "Comfort is a thief that steals the future.",
  "Your daily habits are the absolute monarch of your destiny.",
  "Distraction is the decay of potential.",
  "A quiet grind speaks louder than a roaring boast.",
  "Pain is the toll on the bridge to mastery.",
  "The hardest battles are fought in the theatre of the mind.",
  "Do not mistake motion for progress.",
  "Suffering is mandatory; its purpose is your choice.",
  "We are sculpted by the chisels of our own denials.",
  "The gap between knowing and doing is a graveyard of dreams.",
  "To say yes to greatness is to say no to mediocrity.",
  "An untamed mind is a prison; a disciplined mind is a fortress.",
  "Every ignored responsibility is a debt paid with interest later.",
  "The seed must break its shell to touch the sky.",
  "Willpower is a blade; use it daily or it rusts.",
  "True freedom is found in strict obedience to your own rules.",
  "The fire that warms you can also forge you.",
  "Hesitation is the rust of the soul.",
  "You are the architect of your own ruin or your own rescue.",
  "Let your results be your only defense.",
  "The coward looks for an exit; the warrior looks for a way through.",
  "Sacrifice is merely trading what you want now for what you want most.",
  "Endure the winter of your labor to taste the harvest of your success.",
  "A single step in the dark is worth a thousand miles in the imagination.",
  "The iron does not negotiate with the flame.",
  "Your attention is the currency of your life; spend it wisely.",
  "Consistency turns the frailest thread into a steel cable.",
  "Do not ask the world to be easier; demand yourself to be stronger.",
  "The strongest roots grow in the harshest soil.",
  "Delay is the deadliest form of denial.",
  "A fortress is built one silent stone at a time.",
  "Fear is a shadow; step into the light of action and it vanishes.",
  "The obstacle is not in the way; the obstacle is the forge.",
  "Excellence is a daily rebellion against entropy.",
  "He who cannot obey himself cannot command others.",
  "To seek the truth is to abandon the comfort of the lie.",
  "Every morning is a contract you sign with your own potential.",
  "A life without friction is a life without traction.",
  "The amateur waits for the muse; the professional opens the shop.",
  "Nothing of value is ever born in the shallow end.",
  "Guard your focus as a king guards his crown.",
  "The pain of discipline weighs ounces; the pain of regret weighs tons.",
  "You earn your confidence by keeping the promises you make to yourself.",
  "The loudest storm eventually bows to the quiet mountain.",
  "If you negotiate with weakness, you will always surrender.",
  "Greatness is a lonely road, paved with misunderstood choices.",
  "Let the fatigue of the body sharpen the resolve of the spirit.",
  "A river cuts through rock not because of its power, but its persistence.",
  "We drown not by falling into the river, but by staying submerged.",
  "The cost of leadership is the willingness to walk alone.",
  "Your excuses are the architects of your failures.",
  "Tomorrow is the sanctuary of the defeated.",
  "A sharp knife cuts clean; a focused mind strikes deep.",
  "Do not lower your gaze to the dirt when the stars demand your attention.",
  "The only true failure is the surrender of the will.",
  "Iron sharpens iron, but the fire tempers the blade.",
  "To desire ease is to invite weakness.",
  "The man who loves walking will walk further than the man who loves the destination.",
  "Rest is a weapon, not a retreat.",
  "Adversity is the mirror that reflects your true face.",
  "Every victory was once a dark and uncertain struggle.",
  "You cannot borrow strength; it must be mined from your own depths.",
  "The difference between an ordeal and an adventure is your attitude.",
  "A wandering eye builds a crumbling tower.",
  "Let the critics speak; let the builder work.",
  "He who conquers his impulses wears the invisible crown.",
  "The present moment is the only arena where victory is decided.",
  "To master the storm, you must first master your breath.",
  "An empty vessel makes the most noise; a full one holds its weight.",
  "If the path is easy, it is likely leading nowhere.",
  "Wisdom is the scar tissue of mistakes.",
  "Burn the ships; retreat is an illusion.",
  "The mind is a battlefield; patrol your borders.",
  "What the crowd demands is rarely what the soul requires.",
  "To hold your tongue is often to hold your power.",
  "A daily millimeter is better than an annual mile.",
  "The shadow of fear is larger than the object that casts it.",
  "Perfection is an illusion; progress is a law.",
  "You are the sum of the discomforts you are willing to endure.",
  "The diamond is merely coal that did not quit under pressure.",
  "Let your ambition be a silent engine, not a loud exhaust.",
  "He who chases two rabbits catches neither.",
  "The first step to mastery is the willingness to look foolish.",
  "Solitude is the laboratory of greatness.",
  "A man's true wealth is the poverty of his desires.",
  "The greatest enemy of a good life is the expectation of an easy one.",
  "Routine is the armor that protects your energy.",
  "Do not measure the mountain until you have climbed it.",
  "The strength of the wolf is the pack; the strength of the mind is focus.",
  "We suffer more in imagination than in reality.",
  "A blunt axe requires more strength; sharpen your skills daily.",
  "Patience is the bitter plant that bears sweet fruit.",
  "If you want to take the island, burn the boats.",
  "The deeper the foundation, the taller the tower.",
  "Your potential is an ocean; do not be content playing in the puddles.",
  "Every master was once a disaster.",
  "The only shortcut is doing the work correctly the first time.",
  "A calm sea never produced a skilled sailor.",
  "You cannot outrun your own lack of preparation.",
  "To lead the orchestra, you must turn your back to the crowd.",
  "The arrow must be pulled backward before it can pierce the target.",
  "Value your time, for it is the fabric of your existence.",
  "A mind stretched by a new challenge never returns to its original dimensions.",
  "The man who moves a mountain begins by carrying away small stones.",
  "Do not trade your long-term vision for a short-term thrill.",
  "The hardest step is always the one that crosses the threshold.",
  "An unexamined failure is a wasted lesson.",
  "True strength is lifting others while carrying your own burden.",
  "The sun does not apologize for its heat.",
  "A single purpose concentrates the mind like a magnifying glass in the sun.",
  "We are what we repeatedly do when no one is watching.",
  "The price of clarity is the elimination of the unnecessary.",
  "Let your actions write the autobiography your words could never tell.",
  "The greatest prison is the fear of other people's opinions.",
  "A disciplined diet of thought prevents the obesity of the mind.",
  "To tame the wild beast of the world, first tame the one within.",
  "The map is not the territory; the plan is not the execution.",
  "Only the man who has tasted the bitter root knows the value of the sweet fruit.",
  "Do not pray for a lighter load; train for a stronger back.",
  "The loudest voice in the room is rarely the most dangerous.",
  "A closed mouth gathers no foot, but a closed mind gathers no truth.",
  "We build our cages with the bars of our own complaints.",
  "The flame that burns twice as bright must have twice the fuel.",
  "A half-hearted effort yields a hollow victory.",
  "The master has failed more times than the beginner has even tried.",
  "Do not let the noise of the world drown out the whisper of your conscience.",
  "The sword is useless to the man who lacks the courage to wield it.",
  "Every hour wasted is a brick missing from your fortress.",
  "A resilient soul bends like the willow but holds like the oak.",
  "The cure for the fear of failure is the mechanics of action.",
  "You cannot paint a masterpiece with a dirty brush.",
  "The man who masters his mornings masters his life.",
  "Hardship is the gravel on the road to glory.",
  "To find yourself, you must first lose your reliance on others.",
  "The ego is a fragile shield; humility is impenetrable armor.",
  "A goal without a timeline is just an empty wish.",
  "Do not let the ghosts of yesterday dictate the actions of today.",
  "The most dangerous lie is the one you tell yourself.",
  "A ship in harbor is safe, but that is not what ships are built for.",
  "The only true currency is the depth of your focus.",
  "Let your silence be the anvil on which you hammer out your thoughts.",
  "The path of least resistance leads to the swamp of mediocrity.",
  "A fire requires oxygen; a dream requires effort.",
  "You cannot write a new chapter while reading the old one.",
  "The weight of the world is only heavy if you try to carry it all at once.",
  "A fool demands respect; a wise man commands it through competence.",
  "The greatest battle is not against the enemy without, but the traitor within.",
  "Focus is the art of knowing what to ignore.",
  "To fly, you must let go of the things that weigh you down.",
  "The strongest lock is forged from an unbroken promise.",
  "A single spark of resolve can burn down a forest of doubts.",
  "Do not build a house of cards and complain about the wind.",
  "The deeper the valley, the more breathtaking the peak.",
  "To be everywhere is to be nowhere.",
  "The man who stands for nothing will fall for anything.",
  "A life of purpose is a life of chosen burdens.",
  "The chains of habit are too light to be felt until they are too heavy to be broken.",
  "Do not fear the storm; become the anchor.",
  "The only way out of the fire is through it.",
  "A steady drip of water can hollow out the hardest stone.",
  "The mind is a garden; pull the weeds of doubt daily.",
  "To achieve the impossible, one must first discard the improbable.",
  "The loudest applause usually comes from the cheapest seats.",
  "A warrior does not complain about the weight of his armor.",
  "The bridge between reality and a dream is sweat.",
  "Do not let the shadow of your past darken the light of your future.",
  "The greatest risk is a life lived entirely in the safe zone.",
  "A focused fool can accomplish more than a distracted genius.",
  "The summit is only halfway; you must still survive the descent.",
  "The most powerful weapon on earth is the human soul on fire.",
  "A life lived in fear is a life half-lived.",
  "The anvil never complains about the hammer's blows.",
  "To master the game, you must first learn the rules.",
  "The greatest triumphs are born from the ashes of the worst defeats.",
  "A tree with strong roots laughs at the storm.",
  "Do not mistake the mirror for the soul.",
  "The only true security is the ability to adapt.",
  "A life without struggle is a life without strength.",
  "The man who walks in another's footsteps leaves no tracks of his own.",
  "To find the treasure, you must be willing to dig in the dirt.",
  "The brightest stars are born in the darkest skies.",
  "A ship does not sink because of the water around it, but the water that gets in.",
  "The greatest illusion is the illusion of control.",
  "To heal a wound, you must stop touching it.",
  "The most profound truths are often the simplest.",
  "A river finds its way to the sea by never stopping.",
  "Do not let the fear of striking out keep you from playing the game.",
  "The only true wisdom is in knowing you know nothing.",
  "A life of reaction is a life of slavery.",
  "To truly live, one must be willing to die a little every day.",
  "The greatest freedom is the freedom from the need for validation.",
  "A spark neglected makes a mighty fire.",
  "Do not curse the darkness; light a candle.",
  "The most dangerous enemy is the one you underestimate.",
  "A life without purpose is a ship without a rudder.",
  "To see the stars, you must go into the dark.",
  "The only true wealth is the wealth of the mind.",
  "A single moment of clarity is worth a lifetime of confusion.",
  "Do not let the perfect be the enemy of the good.",
  "The greatest journey begins with a single, deliberate step.",
  "A life of avoidance is a life of slow death.",
  "To build a fire, you must first gather the wood.",
  "The most profound silence is the silence of understanding.",
  "A drop of sweat is a down payment on a dream.",
  "Do not mistake the echo for the original voice.",
  "The greatest strength is the strength to be vulnerable.",
  "A life without risk is a life without reward.",
  "To master the mind is to master the universe.",
  "The most dangerous place is the comfort zone.",
  "A single lie destroys a whole reputation of integrity.",
  "Do not let the noise of the crowd drown out the music of your soul.",
  "The greatest teacher is the pain of experience.",
  "A life of consumption is a life of emptiness.",
  "To find peace, you must first wage war on your own chaos.",
  "The most profound beauty is the beauty of a disciplined life.",
  "A single act of courage can change the course of history.",
  "Do not let the fear of failure stop you from trying.",
  "The greatest weapon is the weapon of a clear conscience.",
  "A life without limits is a life without definition.",
  "To reach the top, you must be willing to start at the bottom.",
  "The most dangerous poison is the poison of resentment.",
  "A single word of truth outweighs a thousand words of deceit.",
  "Do not mistake a detour for a dead end.",
  "The greatest victory is the victory over oneself.",
  "A life of imitation is a life of theft.",
  "To find the light, you must be willing to enter the darkness.",
  "The most profound joy is the joy of self-discovery.",
  "A single seed can sprout a forest.",
  "Do not let the shadows of the past dictate the light of the future.",
  "The greatest treasure is the treasure of a quiet mind.",
  "A life without passion is a life of gray.",
  "To truly see, you must be willing to close your eyes.",
  "The most dangerous illusion is the illusion of permanence.",
  "A single breath can calm a storm.",
  "Do not mistake the messenger for the message.",
  "The greatest power is the power of a focused will.",
  "A life of distraction is a life of fragmentation.",
  "To build a castle, you must be willing to carry the stones.",
  "The most profound truth is the truth of impermanence.",
  "A single step in the right direction is better than a mile in the wrong one.",
  "Do not let the fear of the unknown stop you from exploring.",
  "The greatest gift is the gift of a clear vision.",
  "A life without discipline is a life of chaos.",
  "To find the truth, you must be willing to question everything.",
  "The most dangerous trap is the trap of complacency.",
  "A single drop of water can reflect the entire universe.",
  "Do not mistake the finger pointing at the moon for the moon itself.",
  "The greatest challenge is the challenge of self-mastery.",
  "A life of reaction is a life of lost opportunities.",
  "To build a legacy, you must be willing to sacrifice the present.",
  "The most profound wisdom is the wisdom of simplicity.",
  "A single act of kindness can ripple through eternity.",
  "Do not let the noise of the world silence the whisper of your heart.",
  "The greatest adventure is the adventure of self-exploration.",
  "A life without courage is a life of regret.",
  "To find your voice, you must be willing to speak in the silence.",
  "The most dangerous enemy is the enemy of apathy.",
  "A single ray of light can pierce the darkest night.",
  "Do not mistake the map for the journey.",
  "The greatest strength is the strength of a focused mind.",
  "A life of avoidance is a life of cowardice.",
  "To build a dream, you must be willing to wake up.",
  "The most profound silence is the silence of a calm mind.",
  "A single moment of focus can change a lifetime.",
  "Do not let the fear of judgment stop you from being authentic.",
  "The greatest wealth is the wealth of a clear conscience.",
  "A life without purpose is a life of drifting.",
  "To find your path, you must be willing to get lost.",
  "The most dangerous illusion is the illusion of separation.",
  "A single breath of fresh air can clear a clouded mind.",
  "Do not mistake the surface for the depth.",
  "The greatest power is the power of a disciplined will.",
  "A life of distraction is a life of missed moments.",
  "To build a future, you must be willing to tear down the past.",
  "The most profound truth is the truth of interconnectedness.",
  "A single step forward is better than a thousand steps backward.",
  "Do not let the fear of the future stop you from living in the present.",
  "The greatest gift is the gift of a present mind.",
  "A life without challenge is a life of stagnation.",
  "To find the answer, you must be willing to ask the question.",
  "The most dangerous trap is the trap of self-deception.",
  "A single drop of rain can start a flood.",
  "Do not mistake the symbol for the reality.",
  "The greatest challenge is the challenge of living authentically.",
  "A life of reaction is a life of lost agency.",
  "To build a masterpiece, you must be willing to make a mess.",
  "The most profound wisdom is the wisdom of letting go.",
  "A single act of courage can inspire a generation.",
  "Do not let the noise of the world distract you from the music of the spheres.",
  "The greatest adventure is the adventure of living fully.",
  "Action untethered from purpose is merely exhaustion.",
  "You are exactly where your choices have led you; accept it, then change it.",
  "The ego craves an audience; the spirit craves the work.",
  "A hollow mind fills itself with the opinions of others.",
  "Endure the silence, for it is where your truest self is forged.",
  "The heaviest chains are the ones we willingly place upon our own wrists.",
  "Respect your future self enough to suffer a little today.",
  "We do not rise to our aspirations; we default to our habits.",
  "A master is simply a beginner who refused to stop failing.",
  "Time kills all things, but it immortalizes the disciplined.",
  "Comfort is the invisible poison in the well of greatness.",
  "To demand respect without providing value is the definition of arrogance.",
  "A man who cannot sit alone in a quiet room is a prisoner to his surroundings.",
  "The sharpest blade is useless in the hands of a trembling coward.",
  "Do not measure the day by the clock, but by the ground gained.",
  "The hardest metal requires the hottest flame.",
  "Weakness negotiates; strength dictates.",
  "You cannot conquer the external world until you have subdued the internal one.",
  "To shrink from a challenge is to steal from your own destiny.",
  "The crowd praises the finish line; the master honors the starting block.",
  "A disciplined mind is a sniper; a distracted mind is a shotgun fired blindly.",
  "Let your actions cast a shadow so long that your words are unnecessary.",
  "The road to hell is paved with good intentions; the road to heaven is paved with hard action.",
  "A fortress with unguarded gates is merely a waiting tomb.",
  "Pain is information; do not fear it, decode it.",
  "The amateur craves inspiration; the professional relies on execution.",
  "Do not let the applause of fools convince you that you have arrived.",
  "A life of constant consumption leaves no room for creation.",
  "The summit belongs to the man who ignored the blisters.",
  "You are the sculptor, the chisel, and the marble; chip away the excess.",
  "The greatest betrayal is the betrayal of your own potential.",
  "To ask for an easy life is to ask for a meaningless one.",
  "A mind focused on a single point can burn through any obstacle.",
  "Do not confuse a loud ego with a strong character.",
  "The weight of discipline is measured in grams; the weight of regret is measured in tons.",
  "A warrior does not train for the battle he wants, but for the battle that is coming.",
  "The most expensive thing in the world is a cheap excuse.",
  "Let the friction of the world polish the stone of your resolve.",
  "To conquer the mountain, you must first make peace with the incline.",
  "The fire of ambition must be fed by the logs of daily labor.",
  "A single drop of poison can corrupt a barrel of pure water; guard your thoughts.",
  "The man who expects nothing is prepared for everything.",
  "Do not mistake a comfortable cage for a safe haven.",
  "The highest peaks are surrounded by the thinnest air; prepare to breathe heavily.",
  "A life spent avoiding failure is a life entirely wasted.",
  "To find the source of the river, you must walk against the current.",
  "The most powerful words are the ones you speak to yourself when no one is listening.",
  "A single act of discipline echoes through the corridors of your future.",
  "Do not let the fear of the dark blind you to the stars.",
  "The greatest victory is the one you win silently against your own lethargy.",
  "A life of reaction is a leaf blown by the wind; a life of intention is the wind itself.",
  "To build an empire, you must first learn to lay a single brick perfectly.",
  "The most profound strength is the ability to endure without complaint.",
  "A single spark of defiance can ignite a revolution within the soul.",
  "Do not mistake the shadow of the mountain for the mountain itself.",
  "The greatest challenge is to remain steadfast when the world demands compromise.",
  "A life without focus is a camera without a lens; everything is a blur.",
  "To find your true north, you must ignore the magnetic pull of the crowd.",
  "The most dangerous enemy is the one who convinces you to surrender before the fight begins.",
  "A single drop of sweat shed in preparation saves a gallon of blood in battle.",
  "Do not let the illusion of time convince you that you can wait until tomorrow.",
  "The greatest gift you can give yourself is the brutal honesty of self-assessment.",
  "A life without discipline is a horse without a bridle; it will run wild until it crashes.",
  "To find the treasure of mastery, you must dig through the dirt of repetition.",
  "The final test of a man is what he chooses to do when he finally has nothing left to prove.",
];

/**
 * Get the quote of the day.
 * Uses UTC date to ensure global consistency.
 * @param {string|null} dateStr - Optional date string (YYYY-MM-DD)
 * @returns {Object} Quote object with text, number, index, date, total
 */
function getQuoteOfTheDay(dateStr = null) {
  const START_DATE = new Date("2025-01-01T00:00:00Z");

  let targetDate;
  if (dateStr) {
    // Validate and parse custom date
    const parsed = new Date(dateStr + "T00:00:00Z");
    if (isNaN(parsed.getTime())) {
      throw new Error(`Invalid date format: "${dateStr}". Use YYYY-MM-DD.`);
    }
    targetDate = parsed;
  } else {
    const now = new Date();
    targetDate = new Date(
      Date.UTC(now.getUTCFullYear(), now.getUTCMonth(), now.getUTCDate())
    );
  }

  const daysSinceStart = Math.floor(
    (targetDate - START_DATE) / (1000 * 60 * 60 * 24)
  );

  // Keep the modulo result positive even for dates before START_DATE
  const index =
    ((daysSinceStart % QUOTES.length) + QUOTES.length) % QUOTES.length;

  return {
    text: QUOTES[index],
    number: index + 1,
    index,
    date: targetDate.toISOString().split("T")[0],
    total: QUOTES.length,
  };
}

/**
 * Get a quote by its 1-based number (1–365).
 */
function getQuoteByNumber(n) {
  const index = Math.max(0, Math.min(QUOTES.length - 1, n - 1));
  const startDate = new Date("2025-01-01T00:00:00Z");
  const d = new Date(startDate.getTime() + index * 86400000);
  return {
    text: QUOTES[index],
    number: index + 1,
    index,
    date: d.toISOString().split("T")[0],
    total: QUOTES.length,
  };
}

module.exports = { QUOTES, getQuoteOfTheDay, getQuoteByNumber };
